### ISSUE TITLE
[error] Allow find cause and inspect error without checking key words in error message

### ISSUE THREAD

**Issue by at15** [dyweb/gommon#66]
Currently, error handling is still not very handy, still need to

- get root cause/cause of certain error, we already has wrap (but we have multi error)
- allow library user to inspect the error without calling `strings.Contains(err.Error(), "not exists")`
- categorize error so they can be reported to a central service (like sentry)
- convert error from standard library and `pkg/errors`
- document and example
   - auto update godoc.org after commit (it needs manual refresh ...)

## Ref 

Go

- https://github.com/gaohailang/blog/issues/47 mentioned methods like `Timeout()` in `net` package
  - https://blog.golang.org/errors-are-values
- https://github.com/moby/moby/tree/master/errdefs use interface like `NotImplemented` as causer
- - https://github.com/pingcap/tidb/tree/master/terror have class of error
- hashicorp's error package has some util function for traversing wrapped error `Contains` etc.
- https://github.com/getsentry/raven-go
- https://github.com/aws/aws-sdk-go/tree/master/aws/awserr

Rust

- https://github.com/rust-lang-nursery/failure
- https://doc.rust-lang.org/book/second-edition/ch09-00-error-handling.html

**Comment by at15** [comment]
@gaocegege @codeworm96 any recommendation for error handling in go/rust or any other languages ... @xplorld

**Comment by codeworm96** [comment]
I think errors should be type rich.

**Comment by at15** [comment]
@codeworm96 you mean have an interface and inspect based on type?

**Comment by codeworm96** [comment]
Different errors should be different types/variants of enum (at best effort, though)

**Comment by at15** [comment]
Fixed in #96
